### ISSUE TITLE
Uncaught exception when emulating on browser

### ISSUE THREAD

**Issue by elazarg** [haitham-kablan/Yearly_project#35]
```
main.dart.js:3121 Uncaught MissingPluginException(No implementation found for method getToken on channel plugins.flutter.io/firebase_messaging)
    at Object.a (http://www.hadarsocialnetwork.com/main.dart.js:3121:3)
    at http://www.hadarsocialnetwork.com/main.dart.js:55545:15
    at af7.a (http://www.hadarsocialnetwork.com/main.dart.js:4544:71)
    at af7.$2 (http://www.hadarsocialnetwork.com/main.dart.js:30798:23)
    at aen.$1 (http://www.hadarsocialnetwork.com/main.dart.js:30790:30)
    at OM.nB (http://www.hadarsocialnetwork.com/main.dart.js:31768:41)
    at a9J.$0 (http://www.hadarsocialnetwork.com/main.dart.js:31189:11)
    at Object.rY (http://www.hadarsocialnetwork.com/main.dart.js:4662:40)
    at a9.m_ (http://www.hadarsocialnetwork.com/main.dart.js:31096:3)
    at a9B.$0 (http://www.hadarsocialnetwork.com/main.dart.js:31147:22)
```

**Comment by haitham-kablan** [comment]
This is done , becuase i have migrated the app partly to firebase messagin (as i said before i needed credit card to complete the process) , so this isnt an actaul bug and wont affect the cleint , I will check if I can cancel that migration so the exception wont pop up again
